name: Update Plugins
on:
  schedule:
    - cron: '0 5 * * 1' # Every Monday at 5am

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v16
      - run: ./bin/commit-lockfile-changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
